name: ragged-text-dev
channels:
  - conda-forge
dependencies:
  - cudatoolkit=11.0.3
  - cudnn=8.0.5.39
  - nltk
  - numpy
  - pip
  - pycodestyle
  - pylint
  - python=3.8
  - pip:
    - tensorflow>=2.4.1
    - git+https://github.com/brainsqueeze/text2vec.git