name: ragged-text-dev
channels:
  - anaconda
  - defaults
dependencies:
  - cudatoolkit
  - cudnn  # tensorflow 2.4.1+ needs cuDNN 8+, which isn't available on anaconda yet
  - cupti
  - nltk
  - numpy
  - pip
  - pycodestyle
  - pylint
  # - tensorflow-gpu>=2.2.0
  - pip:
    - tensorflow==2.3.0